import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
      <div className="flex justify-between px-2">
      <h1>Next.js Fullstack App</h1>
      <nav>
          <Link href="/">Home</Link> |{" "}
          <Link href="/dashboard">Dashboard</Link>
      </nav>
      </div>
        {children}
      </body>
    </html>
  );
}
